#!/usr/bin/python3
import logging
import uuid
import boto3
from botocore.exceptions import ClientError

logging.basicConfig(level=logging.INFO)

access_key = "214398ae-11fb-4fe3-b516-3b566973ddfe"
secret_key = "ec0386992ce254382e57ac2a4682b8ae65d794a09322a1054e1a4aea42e0448e"
endpoint_url = "http://docker.messner.click:8000"

client = boto3.client(
        "s3",
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        endpoint_url=endpoint_url
        )
res = client.list_buckets()
for bucket_name in res["Buckets"]:
    print(bucket_name["Name"])
print(f"listing available buckets: {client.list_buckets()}")
for item in ("blockstorage", "filestorage", "webstorage"):
    bucket_name = f"{item}-{str(uuid.uuid4())}"
    print(f"creating bucket for {item} : {bucket_name}")
    client.create_bucket(Bucket=bucket_name)
    res = client.upload_file("./cloudserver_init.py", bucket_name, "init")
    client.download_file(bucket_name, "init", "restore")

